FROM nextflow/nextflow:25.10.4

RUN mkdir -p /opt/prefect

WORKDIR /opt/prefect

COPY requirements.txt .

RUN apt-get install -y \
    python3-pip \
    && rm -rf /var/lib/apt/lists/* \
    && pip install --no-cache-dir -r requirements.txt