FROM nextflow/nextflow:25.10.4

RUN mkdir -p /opt/prefect/src/

WORKDIR /opt/prefect/src

COPY src/* .

COPY requirements.txt .

RUN yum install -y python3-pip \
    && pip install --no-cache-dir -r requirements.txt