FROM nextflow/nextflow:25.10.4

RUN mkdir -p /opt/prefect/

COPY . /opt/prefect/

WORKDIR /opt/prefect/

COPY requirements_nextflow.txt .

RUN yum install -y python3-pip \
    && pip install --no-cache-dir -r requirements_nextflow.txt